"""Add CFExample model.

Revision ID: 09e1f9b33ea2
Revises: c0a26b449b50
Create Date: 2018-01-07 16:38:47.639047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import server

# revision identifiers, used by Alembic.
revision = '09e1f9b33ea2'
down_revision = 'c0a26b449b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cf_example_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cf_example_sets'))
    )
    op.create_table('cf_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('cf_example_set_id', sa.Integer(), nullable=False),
    sa.Column('example_id', server.models.example.GUID(), nullable=False),
    sa.Column('label_1_id', sa.Integer(), nullable=False),
    sa.Column('label_2_id', sa.Integer(), nullable=False),
    sa.Column('label_3_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cf_example_set_id'], ['cf_example_sets.id'], name=op.f('fk_cf_examples_cf_example_set_id_cf_example_sets')),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], name=op.f('fk_cf_examples_example_id_examples')),
    sa.ForeignKeyConstraint(['label_1_id'], ['labels.id'], name=op.f('fk_cf_examples_label_1_id_labels')),
    sa.ForeignKeyConstraint(['label_2_id'], ['labels.id'], name=op.f('fk_cf_examples_label_2_id_labels')),
    sa.ForeignKeyConstraint(['label_3_id'], ['labels.id'], name=op.f('fk_cf_examples_label_3_id_labels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cf_examples'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cf_examples')
    op.drop_table('cf_example_sets')
    # ### end Alembic commands ###
