"""Add Example model.

Revision ID: 3f396a106c10
Revises: 1153a41543e8
Create Date: 2018-01-06 21:46:59.681255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import server

# revision identifiers, used by Alembic.
revision = '3f396a106c10'
down_revision = '1153a41543e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flickr_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flickr_queries'))
    )
    op.create_table('labels',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_labels'))
    )
    op.create_table('examples',
    sa.Column('id', server.models.example.GUID(), nullable=False),
    sa.Column('label_name', sa.String(length=64), nullable=True),
    sa.Column('flickr_query_id', sa.Integer(), nullable=True),
    sa.Column('url_m', sa.String(length=128), nullable=True),
    sa.Column('url_s', sa.String(length=128), nullable=True),
    sa.Column('url_z', sa.String(length=128), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('width_s', sa.Float(), nullable=True),
    sa.Column('width_z', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('height_s', sa.Float(), nullable=True),
    sa.Column('height_z', sa.Float(), nullable=True),
    sa.Column('flickr_data', sa.String(length=2048), nullable=True),
    sa.ForeignKeyConstraint(['flickr_query_id'], ['flickr_queries.id'], name=op.f('fk_examples_flickr_query_id_flickr_queries')),
    sa.ForeignKeyConstraint(['label_name'], ['labels.name'], name=op.f('fk_examples_label_name_labels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examples'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    op.drop_table('labels')
    op.drop_table('flickr_queries')
    # ### end Alembic commands ###
