"""Add Example model.

Revision ID: c0a26b449b50
Revises: 1153a41543e8
Create Date: 2018-01-07 11:28:52.882193

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

import server

# revision identifiers, used by Alembic.
revision = 'c0a26b449b50'
down_revision = '1153a41543e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flickr_query_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flickr_query_sets'))
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('name', name=op.f('uq_labels_name'))
    )
    op.create_table('flickr_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('query', sa.String(length=300), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('per_page', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('flickr_query_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['flickr_query_set_id'], ['flickr_query_sets.id'], name=op.f('fk_flickr_queries_flickr_query_set_id_flickr_query_sets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_flickr_queries'))
    )
    op.create_table('examples',
    sa.Column('id', server.models.example.GUID(), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('label_id', sa.Integer(), nullable=True),
    sa.Column('flickr_query_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('url_m', sa.String(length=128), nullable=True),
    sa.Column('url_s', sa.String(length=128), nullable=True),
    sa.Column('url_z', sa.String(length=128), nullable=True),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('width_s', sa.Float(), nullable=True),
    sa.Column('width_z', sa.Float(), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=True),
    sa.Column('height_s', sa.Float(), nullable=True),
    sa.Column('height_z', sa.Float(), nullable=True),
    sa.Column('flickr_data', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['flickr_query_id'], ['flickr_queries.id'], name=op.f('fk_examples_flickr_query_id_flickr_queries')),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_examples_label_id_labels')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_examples'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('examples')
    op.drop_table('flickr_queries')
    op.drop_table('labels')
    op.drop_table('flickr_query_sets')
    # ### end Alembic commands ###
