"""Add model for ExampleFile.

Revision ID: e9c351e747d4
Revises: 09e1f9b33ea2
Create Date: 2018-01-07 23:19:38.365420

"""
from alembic import op
import sqlalchemy as sa

import server


# revision identifiers, used by Alembic.
revision = 'e9c351e747d4'
down_revision = '09e1f9b33ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('example_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img_path', sa.String(length=300), nullable=True),
    sa.Column('desc_path', sa.String(length=300), nullable=True),
    sa.Column('example_id', server.models.example.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['example_id'], ['examples.id'], name=op.f('fk_example_files_example_id_examples')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_example_files'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('example_files')
    # ### end Alembic commands ###
